name: dotnet-test-build
description: Builds net/DevExtreme.AspNet.Data.sln in Debug configuration, with NuGet cache

runs:
  using: "composite"

  steps:
  # # enable when a next .net preview sdk (not in an image) is needed
  # - uses: actions/setup-dotnet@v4
  #   with:
  #     dotnet-quality: ga
  #     dotnet-version: 10.0

  - uses: actions/cache@v4
    with:
      key: ${{ runner.os }}-nuget-${{ hashFiles('net/**/*.csproj') }}
      restore-keys: ${{ runner.os }}-nuget-
      path: ~/.nuget/packages

  - shell: bash
    run: cd net/Sample && npm i

  - shell: bash
    run: dotnet build -c Debug net/DevExtreme.AspNet.Data.sln
