<?xml version="1.0" encoding="utf-8"?><Database Class="TestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="RemoteGroupingStress_DataItems">
    <Type Name="RemoteGroupingStress_DataItem">
      <Column Name="ID" AutoSync="Never" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Num" Type="System.Int32" CanBeNull="false" />
      <Column Name="NullNum" Type="System.Int32" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="datetime2" CanBeNull="false" />
      <Column Name="NullDate" Type="System.DateTime" DbType="datetime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="RemoteGroupCount_DataItems">
    <Type Name="RemoteGroupCount_DataItem">
      <Column Name="ID" AutoSync="Never" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="G1" Type="System.Int32" CanBeNull="false" />
      <Column Name="G2" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Summary_DataItems">
    <Type Name="Summary_DataItem">
      <Column Name="ID" AutoSync="Never" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Group1" Type="System.String" CanBeNull="true" />
      <Column Name="Group2" Type="System.String" CanBeNull="true" />
      <Column Name="Value" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="GenericTestDataItems">
    <Type Name="GenericTestDataItem">
      <Column Member="ID" AutoSync="Never" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Member="Num" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
</Database>