#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtreme.AspNet.Data.Tests.L2S
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class TestDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRemoteGroupingStress_DataItem(RemoteGroupingStress_DataItem instance);
    partial void UpdateRemoteGroupingStress_DataItem(RemoteGroupingStress_DataItem instance);
    partial void DeleteRemoteGroupingStress_DataItem(RemoteGroupingStress_DataItem instance);
    partial void InsertRemoteGroupCount_DataItem(RemoteGroupCount_DataItem instance);
    partial void UpdateRemoteGroupCount_DataItem(RemoteGroupCount_DataItem instance);
    partial void DeleteRemoteGroupCount_DataItem(RemoteGroupCount_DataItem instance);
    partial void InsertSummary_DataItem(Summary_DataItem instance);
    partial void UpdateSummary_DataItem(Summary_DataItem instance);
    partial void DeleteSummary_DataItem(Summary_DataItem instance);
    partial void InsertGenericTestDataItem(GenericTestDataItem instance);
    partial void UpdateGenericTestDataItem(GenericTestDataItem instance);
    partial void DeleteGenericTestDataItem(GenericTestDataItem instance);
    #endregion
		
		public TestDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RemoteGroupingStress_DataItem> RemoteGroupingStress_DataItems
		{
			get
			{
				return this.GetTable<RemoteGroupingStress_DataItem>();
			}
		}
		
		public System.Data.Linq.Table<RemoteGroupCount_DataItem> RemoteGroupCount_DataItems
		{
			get
			{
				return this.GetTable<RemoteGroupCount_DataItem>();
			}
		}
		
		public System.Data.Linq.Table<Summary_DataItem> Summary_DataItems
		{
			get
			{
				return this.GetTable<Summary_DataItem>();
			}
		}
		
		public System.Data.Linq.Table<GenericTestDataItem> GenericTestDataItems
		{
			get
			{
				return this.GetTable<GenericTestDataItem>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class RemoteGroupingStress_DataItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Num;
		
		private System.Nullable<int> _NullNum;
		
		private System.DateTime _Date;
		
		private System.Nullable<System.DateTime> _NullDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNumChanging(int value);
    partial void OnNumChanged();
    partial void OnNullNumChanging(System.Nullable<int> value);
    partial void OnNullNumChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnNullDateChanging(System.Nullable<System.DateTime> value);
    partial void OnNullDateChanged();
    #endregion
		
		public RemoteGroupingStress_DataItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num")]
		public int Num
		{
			get
			{
				return this._Num;
			}
			set
			{
				if ((this._Num != value))
				{
					this.OnNumChanging(value);
					this.SendPropertyChanging();
					this._Num = value;
					this.SendPropertyChanged("Num");
					this.OnNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NullNum")]
		public System.Nullable<int> NullNum
		{
			get
			{
				return this._NullNum;
			}
			set
			{
				if ((this._NullNum != value))
				{
					this.OnNullNumChanging(value);
					this.SendPropertyChanging();
					this._NullNum = value;
					this.SendPropertyChanged("NullNum");
					this.OnNullNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="datetime2")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NullDate", DbType="datetime2")]
		public System.Nullable<System.DateTime> NullDate
		{
			get
			{
				return this._NullDate;
			}
			set
			{
				if ((this._NullDate != value))
				{
					this.OnNullDateChanging(value);
					this.SendPropertyChanging();
					this._NullDate = value;
					this.SendPropertyChanged("NullDate");
					this.OnNullDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class RemoteGroupCount_DataItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _G1;
		
		private int _G2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnG1Changing(int value);
    partial void OnG1Changed();
    partial void OnG2Changing(int value);
    partial void OnG2Changed();
    #endregion
		
		public RemoteGroupCount_DataItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G1")]
		public int G1
		{
			get
			{
				return this._G1;
			}
			set
			{
				if ((this._G1 != value))
				{
					this.OnG1Changing(value);
					this.SendPropertyChanging();
					this._G1 = value;
					this.SendPropertyChanged("G1");
					this.OnG1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G2")]
		public int G2
		{
			get
			{
				return this._G2;
			}
			set
			{
				if ((this._G2 != value))
				{
					this.OnG2Changing(value);
					this.SendPropertyChanging();
					this._G2 = value;
					this.SendPropertyChanged("G2");
					this.OnG2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Summary_DataItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Group1;
		
		private string _Group2;
		
		private System.Nullable<int> _Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGroup1Changing(string value);
    partial void OnGroup1Changed();
    partial void OnGroup2Changing(string value);
    partial void OnGroup2Changed();
    partial void OnValueChanging(System.Nullable<int> value);
    partial void OnValueChanged();
    #endregion
		
		public Summary_DataItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group1")]
		public string Group1
		{
			get
			{
				return this._Group1;
			}
			set
			{
				if ((this._Group1 != value))
				{
					this.OnGroup1Changing(value);
					this.SendPropertyChanging();
					this._Group1 = value;
					this.SendPropertyChanged("Group1");
					this.OnGroup1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group2")]
		public string Group2
		{
			get
			{
				return this._Group2;
			}
			set
			{
				if ((this._Group2 != value))
				{
					this.OnGroup2Changing(value);
					this.SendPropertyChanging();
					this._Group2 = value;
					this.SendPropertyChanged("Group2");
					this.OnGroup2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value")]
		public System.Nullable<int> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class GenericTestDataItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Num;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNumChanging(int value);
    partial void OnNumChanged();
    #endregion
		
		public GenericTestDataItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num")]
		public int Num
		{
			get
			{
				return this._Num;
			}
			set
			{
				if ((this._Num != value))
				{
					this.OnNumChanging(value);
					this.SendPropertyChanging();
					this._Num = value;
					this.SendPropertyChanged("Num");
					this.OnNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
